// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEPDKOX1nt7g5xEncluFtyRrPNyXd6vs',
    appId: '1:158707930467:web:dae742fb2c98dd6b9f6f56',
    messagingSenderId: '158707930467',
    projectId: 'recipe-8b1e8',
    authDomain: 'recipe-8b1e8.firebaseapp.com',
    storageBucket: 'recipe-8b1e8.appspot.com',
    measurementId: 'G-RZW4XLEP9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIqmBULGSUsyu3_HIcY3uzMiA2PdEK4o',
    appId: '1:158707930467:android:f337013955537e5b9f6f56',
    messagingSenderId: '158707930467',
    projectId: 'recipe-8b1e8',
    storageBucket: 'recipe-8b1e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLfvsfbWUZwyXKTYHo7hzMsuyTYPcBRE',
    appId: '1:158707930467:ios:63dac2bd2f5ef3be9f6f56',
    messagingSenderId: '158707930467',
    projectId: 'recipe-8b1e8',
    storageBucket: 'recipe-8b1e8.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLfvsfbWUZwyXKTYHo7hzMsuyTYPcBRE',
    appId: '1:158707930467:ios:63dac2bd2f5ef3be9f6f56',
    messagingSenderId: '158707930467',
    projectId: 'recipe-8b1e8',
    storageBucket: 'recipe-8b1e8.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrEPDKOX1nt7g5xEncluFtyRrPNyXd6vs',
    appId: '1:158707930467:web:f75c1e09c46f991d9f6f56',
    messagingSenderId: '158707930467',
    projectId: 'recipe-8b1e8',
    authDomain: 'recipe-8b1e8.firebaseapp.com',
    storageBucket: 'recipe-8b1e8.appspot.com',
    measurementId: 'G-DWP61NR4MM',
  );
}
